"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-25 10:21:43.714789
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_cache",
        sa.Column("key", sa.String(length=512), nullable=False),
        sa.Column("namespace", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=True),
        sa.Column("source_version", sa.String(length=32), nullable=True),
        sa.Column("cache_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cache_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    with op.batch_alter_table("api_cache", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_cache_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_api_cache_namespace"), ["namespace"], unique=False)

    op.create_table(
        "manual_reviews",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=32), nullable=True),
        sa.Column("source_platform", sa.String(length=16), nullable=False),
        sa.Column("source_key", sa.String(length=64), nullable=False),
        sa.Column("target_platform", sa.String(length=16), nullable=False),
        sa.Column("target_key", sa.String(length=64), nullable=False),
        sa.Column("target_display", sa.String(length=128), nullable=True),
        sa.Column("verdict", sa.String(length=16), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("matching_engine_version", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_platform", "source_key", "target_platform", "target_key", name="uq_manual_review_pair"
        ),
    )
    op.create_table(
        "match_candidates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=32), nullable=True),
        sa.Column("source_platform", sa.String(length=16), nullable=False),
        sa.Column("source_key", sa.String(length=64), nullable=False),
        sa.Column("target_platform", sa.String(length=16), nullable=False),
        sa.Column("target_key", sa.String(length=64), nullable=False),
        sa.Column("discovered_via", sa.JSON(), nullable=True),
        sa.Column("decision", sa.String(length=16), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("evidence_json", sa.JSON(), nullable=True),
        sa.Column("matching_engine_version", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("match_candidates", schema=None) as batch_op:
        batch_op.create_index("ix_candidates_source", ["source_platform", "source_key"], unique=False)

    op.create_table(
        "match_decisions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=32), nullable=True),
        sa.Column("source_platform", sa.String(length=16), nullable=False),
        sa.Column("source_key", sa.String(length=64), nullable=False),
        sa.Column("source_account_id", sa.String(length=64), nullable=True),
        sa.Column("target_platform", sa.String(length=16), nullable=False),
        sa.Column("target_key", sa.String(length=64), nullable=True),
        sa.Column("target_account_id", sa.String(length=64), nullable=True),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("evidence_json", sa.JSON(), nullable=True),
        sa.Column("matching_engine_version", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("match_decisions", schema=None) as batch_op:
        batch_op.create_index("ix_decisions_source", ["source_platform", "source_key"], unique=False)

    op.create_table(
        "platform_accounts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("platform_user_id", sa.String(length=64), nullable=True),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("username_key", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=True),
        sa.Column("profile_url", sa.String(length=512), nullable=True),
        sa.Column("profile_image_url", sa.String(length=1024), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column("category", sa.String(length=255), nullable=True),
        sa.Column("stream_title", sa.Text(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("raw_json", sa.JSON(), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform", "username_key", name="uq_account_platform_username"),
    )
    op.create_table(
        "processing_jobs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("stored_path", sa.String(length=1024), nullable=False),
        sa.Column("output_path", sa.String(length=1024), nullable=True),
        sa.Column("review_path", sa.String(length=1024), nullable=True),
        sa.Column("source_platform", sa.String(length=16), nullable=True),
        sa.Column("detected_platform", sa.String(length=16), nullable=True),
        sa.Column("detection_note", sa.Text(), nullable=True),
        sa.Column("sheet_name", sa.String(length=255), nullable=True),
        sa.Column("header_row", sa.Integer(), nullable=True),
        sa.Column("columns_json", sa.JSON(), nullable=True),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("processed_rows", sa.Integer(), nullable=False),
        sa.Column("match_count", sa.Integer(), nullable=False),
        sa.Column("no_match_count", sa.Integer(), nullable=False),
        sa.Column("review_count", sa.Integer(), nullable=False),
        sa.Column("not_found_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("skipped_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("warnings_json", sa.JSON(), nullable=True),
        sa.Column("verification_json", sa.JSON(), nullable=True),
        sa.Column("export_stale", sa.Boolean(), nullable=False),
        sa.Column("matching_engine_version", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("processing_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_processing_jobs_status"), ["status"], unique=False)

    op.create_table(
        "profile_images",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=True),
        sa.Column("username_key", sa.String(length=64), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("phash", sa.String(length=64), nullable=True),
        sa.Column("features_json", sa.JSON(), nullable=True),
        sa.Column("low_complexity", sa.Boolean(), nullable=False),
        sa.Column("fetch_error", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    with op.batch_alter_table("profile_images", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_profile_images_phash"), ["phash"], unique=False)

    op.create_table(
        "processing_rows",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=32), nullable=False),
        sa.Column("original_row", sa.Integer(), nullable=False),
        sa.Column("source_value", sa.String(length=512), nullable=True),
        sa.Column("source_key", sa.String(length=64), nullable=True),
        sa.Column("country", sa.String(length=128), nullable=True),
        sa.Column("existing_destination", sa.String(length=512), nullable=True),
        sa.Column("existing_remarks", sa.String(length=512), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("source_status", sa.String(length=24), nullable=True),
        sa.Column("target_status", sa.String(length=24), nullable=True),
        sa.Column("decision", sa.String(length=16), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("matched_id", sa.String(length=128), nullable=True),
        sa.Column("review_candidate", sa.String(length=128), nullable=True),
        sa.Column("output_destination", sa.String(length=512), nullable=True),
        sa.Column("output_remarks", sa.String(length=512), nullable=True),
        sa.Column("write_destination", sa.Boolean(), nullable=False),
        sa.Column("write_remarks", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("evidence_json", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("manual_verdict", sa.String(length=16), nullable=True),
        sa.Column("matching_engine_version", sa.String(length=32), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["processing_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "original_row", name="uq_row_job_original_row"),
    )
    with op.batch_alter_table("processing_rows", schema=None) as batch_op:
        batch_op.create_index("ix_rows_job_key", ["job_id", "source_key"], unique=False)
        batch_op.create_index("ix_rows_job_status", ["job_id", "status"], unique=False)

    op.create_table(
        "social_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("identity", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=True),
        sa.Column("unique_identity", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["platform_accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("social_links", schema=None) as batch_op:
        batch_op.create_index("ix_social_kind_identity", ["kind", "identity"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("social_links", schema=None) as batch_op:
        batch_op.drop_index("ix_social_kind_identity")

    op.drop_table("social_links")
    with op.batch_alter_table("processing_rows", schema=None) as batch_op:
        batch_op.drop_index("ix_rows_job_status")
        batch_op.drop_index("ix_rows_job_key")

    op.drop_table("processing_rows")
    with op.batch_alter_table("profile_images", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_profile_images_phash"))

    op.drop_table("profile_images")
    with op.batch_alter_table("processing_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_processing_jobs_status"))

    op.drop_table("processing_jobs")
    op.drop_table("platform_accounts")
    with op.batch_alter_table("match_decisions", schema=None) as batch_op:
        batch_op.drop_index("ix_decisions_source")

    op.drop_table("match_decisions")
    with op.batch_alter_table("match_candidates", schema=None) as batch_op:
        batch_op.drop_index("ix_candidates_source")

    op.drop_table("match_candidates")
    op.drop_table("manual_reviews")
    with op.batch_alter_table("api_cache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_cache_namespace"))
        batch_op.drop_index(batch_op.f("ix_api_cache_expires_at"))

    op.drop_table("api_cache")
    # ### end Alembic commands ###
